name: Deploy Flappy Irys

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    - run: npm test --if-present
    
    - name: Test server startup
      run: |
        timeout 10s npm start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      
  deploy-github-pages:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Create static build
      run: |
        mkdir -p static
        cp index.html static/
        cp style.css static/
        cp script.js static/
        cp -r images static/ 2>/dev/null || true
        
        # Modify script.js for GitHub Pages (remove server dependencies)
        sed -i 's|http://localhost:3000/api|https://api.flappy-irys.com/api|g' static/script.js || true
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./static
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2 